server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${db_url}/demo
    username: ${db_username}
    password: ${db_password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect