server:
  port: 8080

spring:
  datasource:
    # db_url = localhost:3306/demo
    url: jdbc:mysql://${db_url}
    # db_user = root
    username: ${db_username}
    # db_password = root
    password: ${db_password}

  jpa:
    generate-ddl: false
    show-sql: true

    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    check-location: true
    locations: classpath:db/migration
